[workspace]
members = ["fc-server", "fc-command", "fc-desktop"]

[workspace.dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
bincode = "2.0.0-rc.3"
thiserror = "1.0.49"
anyhow = "1.0.75"
log = "0.4.20"
pretty_env_logger = "0.5.0"